services:
  fastapi-app:
    container_name: fastapi-app
    build: .
    image: book-shelf:latest
    command: uvicorn app.main:app --host 0.0.0.0
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mysql-db

  mysql-db:
    container_name: mysql-db
    image: mysql:8.0.43
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: