import { cn } from 'cn';
import type { Metadata } from 'next';
import { Geist } from 'next/font/google';

import { Toaster } from '@/ui/toast';

import './globals.css';

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Bookshelf',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={cn('font-sans', geist.variable)}>
      <body className="dark">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
