import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Bookshelf',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en">
      <body className="dark flex min-h-full flex-col">{children}</body>
    </html>
  );
}
