volumes:
  postgres-data:

services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:5-24-trixie
    volumes:
      - ../..:/workspaces:cached
      
    command: sleep infinity
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

networks:
  app-network:
    driver: bridge
