"""remove isbn and publisher from book

Revision ID: 029160c69d9c
Revises: a8e71675b4ff
Create Date: 2026-02-25 20:02:08.715608

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "029160c69d9c"
down_revision: Union[str, Sequence[str], None] = "a8e71675b4ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("book", sa.Column("published_year", sa.Integer(), nullable=False))
    op.drop_index(op.f("ISBN"), table_name="book")
    op.drop_column("book", "ISBN")
    op.drop_column("book", "publish_year")
    op.drop_column("book", "publisher")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book", sa.Column("publisher", mysql.VARCHAR(length=255), nullable=False)
    )
    op.add_column(
        "book",
        sa.Column("publish_year", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column("book", sa.Column("ISBN", mysql.VARCHAR(length=13), nullable=False))
    op.create_index(op.f("ISBN"), "book", ["ISBN"], unique=True)
    op.drop_column("book", "published_year")
    # ### end Alembic commands ###
