"""enable description nullable

Revision ID: 2e66a5e3a47e
Revises: 029160c69d9c
Create Date: 2026-02-25 20:30:24.832366

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "2e66a5e3a47e"
down_revision: Union[str, Sequence[str], None] = "029160c69d9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "book", "description", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "book", "description", existing_type=mysql.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
