"""add cover_img col into book

Revision ID: 4d3afdcde408
Revises: 2624d6753eb3
Create Date: 2026-09-15 13:41:32.428994

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d3afdcde408"
down_revision: Union[str, Sequence[str], None] = "2624d6753eb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book",
        sa.Column("cover_img", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book", "cover_img")
    # ### end Alembic commands ###
