"""Create author table

Revision ID: 70d1f81597f6
Revises: 8a890af98f6e
Create Date: 2026-04-26 20:28:16.480818

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "70d1f81597f6"
down_revision: Union[str, Sequence[str], None] = "8a890af98f6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("book", sa.Column("author_id", sa.Integer(), nullable=True))
    op.create_foreign_key("fk_book_author", "book", "author", ["author_id"], ["id"])
    op.drop_column("book", "author")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book", sa.Column("author", mysql.VARCHAR(length=255), nullable=False)
    )
    op.drop_constraint("fk_book_author", "book", type_="foreignkey")
    op.drop_column("book", "author_id")
    op.drop_table("author")
    # ### end Alembic commands ###
