"""Create genre table

Revision ID: 8a890af98f6e
Revises: adfaf06de7cd
Create Date: 2026-04-26 11:25:22.674523

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "8a890af98f6e"
down_revision: Union[str, Sequence[str], None] = "adfaf06de7cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genre",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("genre", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("genre"),
    )
    op.add_column("book", sa.Column("genre_id", sa.Integer(), nullable=True))
    op.create_foreign_key("fk_book_genre", "book", "genre", ["genre_id"], ["id"])
    op.drop_column("book", "genre")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("book", sa.Column("genre", mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint("fk_book_genre", "book", type_="foreignkey")
    op.drop_column("book", "genre_id")
    op.drop_table("genre")
    # ### end Alembic commands ###
