"""Add updated_at column

Revision ID: adfaf06de7cd
Revises: 2e66a5e3a47e
Create Date: 2026-04-19 19:36:28.424754

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "adfaf06de7cd"
down_revision: Union[str, Sequence[str], None] = "2e66a5e3a47e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("book", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book", "updated_at")
    # ### end Alembic commands ###
